### ISSUE TITLE
Removed individual accounts from SampleMvcWebApp

### ISSUE THREAD

**Issue by JonPSmith** [JonPSmith/SampleMvcWebApp#3]
Hi @riffrack,

You mentioned a few weeks ago that SampleMvcWebApp has individual account running in the App. I realised that was from a former usage of SampleMvcWebApp and isn't needed any more. I therefore removed the code and turned that feature off because it a) could confuse people and b) it created a accounts database for no reason.

**Comment by riffrack** [comment]
thanks b) is what happened to me

**Comment by JonPSmith** [comment]
Hi @riffrack,

Yep, sorry about that. GenericServices has gone through a lot of changes so this sample can be a bit cluttered. The new sample [SampleMvcWebAppComplex](https://github.com/JonPSmith/SampleMvcWebAppComplex) is actually cleaner, albeit a lot more complex, because it is so recent.
